config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :users, only: [] do
    resources :posts, only: [:index]
  end

  resources :posts
  resources :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include CommonMethods

  belongs_to :user
  belongs_to :post

  validates :body, :post_id, :user_id, presence: true

  def editing?
    Time.now - created_at < 15.minutes
  end
end

app/models/concerns/common_methods.rb
module CommonMethods
  extend ActiveSupport::Concern

  def managed_by?(user)
    user && (user.id == user_id)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include CommonMethods

  acts_as_taggable

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :body, presence: true

  paginates_per 5

  scope :published, -> {where(published: true)}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_posts_path(resource.id)
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :check_access, only: [:edit, :update, :destroy]
  before_action :check_before_edit, only: [:edit, :update, :destroy]


  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.js {}
      else
        format.js {render :new}
      end
    end
  end

  def edit
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.js {}
      else
        format.js { render :edit }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment_id = @comment.id
    @comment.destroy
    respond_to do |format|
      format.js {}
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.fetch(:comment, {}).permit(:body, :post_id, :user_id)
    end

  def check_access
    unless @comment.managed_by?(current_user)
      flash[:warning] = 'You need permission to perform this action.'
      redirect_to post_path @comment.post
    end
  end

  def check_before_edit
    unless @comment.editing?
      respond_to do |format|
        @msg = "You can't edit comment if it was created more than 15 minutes ago."
        format.html {
          flash[:warning] = @msg
          redirect_to @comment.post
        }
        format.js {render :time_is_over}
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_access, only: [:edit, :update, :destroy]
  before_action :tag_cloud, only: [:index]
  before_action :post_tag_cloud, only: [:show]

  def index
    if params[:user_id].present?
      @posts = Post.where(user_id: params[:user_id].to_i)
    else
      @posts = params[:tag].present? ? Post.tagged_with(params[:tag]) : @posts = Post.all
      @posts = @posts.published
    end

    @posts = @posts.includes(:user).order('created_at desc').page params[:page]
  end

  def show
    if !@post.managed_by?(current_user) && !@post.published
      flash[:warning] = "You can't read unpublished post."
      redirect_to root_path
    end
    @comments = @post.comments.order('created_at asc')
    @comment = Comment.new(post: @post)
    @related_posts = @post.find_related_tags.published
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to user_posts_path(current_user), notice: 'Post was successfully destroyed.'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      data = params.fetch(:post, {}).permit(:body, :published, :created_at, tag_list: [])
      data['tag_list']= data['tag_list'].reject(&:blank?).uniq.join(',')
      data
    end

    def check_access
      unless @post.managed_by?(current_user)
        flash[:warning] = 'You need permission to perform this action.'
        redirect_to root_path
      end
    end

    def post_tag_cloud
      @tags = @post.tag_counts_on(:tags)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def created_at_format(resource, format=nil)
    if resource.respond_to?(:created_at)
      resource.created_at.strftime(format ? format : "%d.%m.%Y %H:%M")
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper

  def it_is_my_posts_list
    current_user && (params[:user_id].to_i == current_user.id)
  end
end

app/views/comments/_comment.html.slim
.row
  .col-md-12.comment-wrapper id="comment-wrapper-#{comment.id}"
    .row
      .col-md-9.col-sm-9
        .author id="show-comment-#{comment.id}"
          i class="fa fa-user" aria-hidden="true"
          = comment.user.email
        .pl-20.mt-10
          .comment id="comment-#{comment.id}" = comment.body

      .col-md-3.col-sm-3
        .created_at.text-right
          = created_at_format comment
        - if comment.managed_by?(current_user) && comment.editing?
          span.manage_links.pull-right.mt-10
            = link_to edit_comment_path(comment), class: 'edit-comment-link' do
              i class="fa fa-pencil" aria-hidden="true"
            = link_to comment_path(comment), method: :delete, remote: true, data: {confirm: 'Are you sure?'}, class: 'destroy-comment-link' do
              i class="fa fa-times" aria-hidden="true"

    hr

app/views/comments/_form.html.slim
= simple_form_for(comment, remote: true, format: :js) do |f|
  = f.error_notification

  = f.input :body, label: false
  = f.input :post_id, as: :hidden
  = f.input :user_id, as: :hidden, input_html: {value: current_user ? current_user.id : nil}

  .form-actions
    = f.button :submit

app/views/comments/create.js.erb
$('#comments_wrapper').append("<%= escape_javascript(render 'comment', comment: @comment) %>");
$('#comment_body').val("");
$('.alert-danger').remove();
$('.has-error').removeClass('has-error');
$('.help-block').remove();

app/views/comments/destroy.js.erb
$('#comment-wrapper-'+"<%= @comment_id %>").remove();
Blog.flashes.showMsg('notice', 'Comment was destroyed succesfully.');

app/views/comments/edit.js.erb
$('#comment_form_wrapper').html("<%= escape_javascript(render 'form', comment: @comment) %>");

app/views/comments/edit.slim
- content_for :header do
  | Editing comment

= link_to post_path(@comment.post, {anchor: "show-comment-#{@comment.id}"}) do
  i class="fa fa-long-arrow-left" aria-hidden="true"
  '
  | show post

#comment_form_wrapper.mt-20
  = render 'form', comment: @comment

app/views/comments/index.html.slim
- comments.each do |comment|
  = render 'comments/comment', comment: comment

app/views/comments/new.js.erb
$('#comment_form_wrapper').html("<%= escape_javascript(render 'form', comment: @comment) %>");

app/views/comments/time_is_over.js.erb
Blog.flashes.showMsg('warning', "<%= @msg %>");

app/views/comments/update.js.erb
$('.alert-danger').remove();
$('.has-error').removeClass('has-error');
$('.help-block').remove();
Blog.flashes.showMsg('notice', 'Comment was updated succesfully.');

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Blog"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to 'Blog', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li = link_to "All Posts", root_path
          - if current_user
            ul.nav.navbar-nav
              li= link_to "My Posts", user_posts_path(current_user.id)
            ul.nav.navbar-nav.nav-right
              li
                a
                  i class="fa fa-user" aria-hidden="true"
                  '
                  = current_user.email
              li = link_to "Sign out", destroy_user_session_path, :method => :delete, id: 'sign-out-link', class: 'logout_link'
          - else
            ul.nav.navbar-nav.nav-right
              li = link_to "Log in", new_user_session_path, id: 'log-in-link'
              li = link_to "Sign up", new_user_registration_path, id: 'sign-up-link'

    .container
      .row#main-content
        .col-lg-12
          #bootstrap_flashes
            = bootstrap_flash
          - if content_for?(:header)
            .page-header
              h1 = yield :header
          = yield

      footer
        p &copy; Blog 2016

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification

  = f.input :body, label: 'Text'

  / редактирование
  - if @post.persisted?
    / смена даты создания
    = f.input :created_at, as: :datetime
  - else
    / создание
    .form-group.boolean
      div class="checkbox"
        label class="boolean optional" for="without_publication"
          input class="boolean optional" type="checkbox"  id="without_publication" onclick="Blog.posts.switchPublished($(this), $('#post_published'));" Without publication

  / при создании можно выставить "не публиковать" чек боксом выше (этот будет скрыт)
  / при редактировании можно поставить галку - "Опубликованный", если еще не опублкован (показываем чекбокс)
  = f.input :published, as: ((@post.persisted? && !@post.published) ? :boolean : :hidden), input_html: {checked: @post.published}

  = render 'tags', f: f

  .form-actions
    = f.button :submit

app/views/posts/_post.html.slim
.row
  .col-md-12.post-wrapper id="post-#{post.id}"
    .row
      .col-md-9.col-sm-9
        .author
          i class="fa fa-user" aria-hidden="true"
          = post.user.email
        .pl-20
          .post-body = post.body.truncate(300)

      .col-md-3.col-sm-3
        .created_at.text-right
          = created_at_format post
        - if it_is_my_posts_list
          .text-right.published
            span
              'Published:
              i.fa class="#{post.published ? 'fa-check-square-o' : 'fa-square-o'}" aria-hidden="true"

    .row
      .col-md-12
        span.pl-20 = link_to 'Show more', post

        - if post.managed_by?(current_user)
          span.action_links.pull-right
            = link_to edit_post_path(post), class: 'edit-link' do
              i class="fa fa-pencil" aria-hidden="true"
            = link_to post, method: :delete, id: "delete-#{post.id}", data: {confirm: 'Are you sure?'}, class: 'destroy-link' do
              i class="fa fa-times" aria-hidden="true"
    hr

app/views/posts/_tags.html.slim
#tags_wrapper
  .form-group.string.optional.post_tag_list
    label.string.optional.control-label Tag list
    #tags
      - @post.tag_list.each_with_index do |tag, i|
        .tag
          input name="post[tag_list][]" value="#{tag}" type="hidden"
          span class="visible-tag"
            span = tag
            i class="fa fa-times" aria-hidden="true" onclick="Blog.posts.deleteTag($(this));"

    .tag.tag_template
      input name="post[tag_list][]"  type="hidden"
      span class="visible-tag"
        span
        i class="fa fa-times" aria-hidden="true" onclick="Blog.posts.deleteTag($(this));"

  .clearfix
  / видимое поле ввода новых тэгов
  = f.input :tag_list, input_html: {id: 'enter_tag', name: '', value: '', placeholder: 'Type word and press Enter'}, label: 'Add new tag'

app/views/posts/edit.html.slim
- content_for :header do
  | Editing post

= render 'form'

app/views/posts/index.html.slim
- content_for :header do
  = it_is_my_posts_list ? 'My Posts' : 'Posts'

  - if it_is_my_posts_list
    = link_to new_post_path, class: 'btn btn-primary btn-header' do
      span.glyphicon.glyphicon-plus
      |  New Post

- if @posts.any?
  - if !it_is_my_posts_list && @tags.any?
    = render 'shared/tag_cloud', tags: @tags

  .mt-35
  = render @posts
- else
  p No posts

= paginate @posts, :theme => 'twitter-bootstrap-3'

app/views/posts/new.html.slim
- content_for :header do
  |New post

= render 'form'

app/views/posts/show.html.slim
- content_for :header do
  | Show post

  - if current_user && (current_user.id == @post[:user_id].to_i)
    = link_to edit_post_path(@post), class: 'btn btn-primary btn-header', id: 'edit-post-link' do
      span.glyphicon.glyphicon-pencil
      |Edit post

- if @tags.any?
  = render 'shared/tag_cloud', tags: @tags

.row#show-post-wrapper
  .col-md-9.col-sm-9
    h4 Post:
    em id="post-#{@post.id}" = @post.body
  .col-md-3.col-sm-3
    p.created_at.text-right = created_at_format @post


h4.mt-30 Comments:
hr

#comments_wrapper
  = render template: 'comments/index', locals: {comments: @comments}

.mt-40

- if @post.published
  #comment_form_wrapper
    = render 'comments/form', comment: @comment
- else
  p You can't add comments to unpublished post.

- if @related_posts.length > 0
  #tag_cloud.mt-40
    h4
      'Related posts:
      ul
      - @related_posts.each do |post|
        li.related_post = link_to post.body.truncate(120), post_path(post), id: "related-post-#{post.id}"

app/views/shared/_tag_cloud.slim
#tag_cloud
  h4
    'Tags:
    - tag_cloud(tags, %w(css1 css2 css3 css4)) do |tag, css_class|
      = link_to tag.name, posts_path(tag: tag.name), :class => css_class
  hr